name: Build Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build HTTP container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/promosquad/docker-dev:latest
            ghcr.io/promosquad/docker-dev:${{ github.sha }}
